---
name: default
kind: pipeline
type: docker

platform:
  arch: amd64
  os: linux

steps:
  - name: test
    image: selenium/node-base
    commands:
      - npm install
      - xvfb-run npm run test
